name: Build and Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/xcraftman52/troop711/troop711:latest

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Push Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: XCraftMan52/troop711/troop711
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: latest

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: IMAGE_NAME  # <--- important to pass env var to remote shell
          script: |
            cd /home/${{ secrets.VPS_USER }}/docker/apps/troop711
            docker login ghcr.io -u ${{ secrets.USERNAME }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull $IMAGE_NAME
            docker compose stop troop711
            docker compose rm -f troop711
            docker system prune -f
            docker compose up troop711 -d
